### ISSUE TITLE
DOI redirect doesn't match uuid URL

### ISSUE THREAD

**Issue by J535D165** [4TUResearchData/djehuty#11]
Hi folks. Great to see this replacement of Figshare. 

Please consider the following DOI: https://doi.org/10.4121/21989216.v1. It points to https://data.4tu.nl/articles/_/21989216/1. In your system, this record is found under the URL https://data.4tu.nl/datasets/17e3e0e3-55a2-47d0-bc22-4cb470f3882b. This URL also points to the same resource: https://data.4tu.nl/articles/dataset/Data_on_the_geographical_distribution_of_Mimosa_bimucronata_in_China/21989216. 

The REST API is also not unique: https://data.4tu.nl/v2/articles/17e3e0e3-55a2-47d0-bc22-4cb470f3882b/files and https://data.4tu.nl/v2/articles/21989216/files. 

I think it is better to redirect the URLs to a single source of truth. 

Thanks, Jonathan

(I'm the developer of [Datahugger](https://github.com/J535D165/datahugger) and I struggle to support the new djehuty repo. The former repo worked.)

**Comment by roelj** [comment]
Hi @J535D165 

Thanks for observing this.  To add a bit to this observation: We've discontinued the use of numeric identifiers in favor of the UUIDs. Datasets from the post-Figshare era will not receive numeric identifiers. However, we kept the numeric identifiers for datasets from the Figshare era to remain backward-compatible.

We move cautiously towards the UUIDs to ensure "old" URLs work as expected. Thank you for suggesting using redirects to make sure we end up at a single URL for a dataset.

What issue are you running into exactly with Datahugger?

**Comment by J535D165** [comment]
Thanks for the answer @roelj! Sounds good. 

For Datahugger, the main challenge is content negotiation. Datahugger receives a DOI or URL from the user and then has to find the API endpoint and the dataset identifier. There is no widely adapted protocol to do this, so Datahugger implements this for 350 data repositories. The current implementation looks like this: https://j535d165.github.io/datahugger/working/. Back to Djehuty, there are now multiple dataset identifiers, so Datahugger struggles to find the correct one because it currently supports only one "identifier resolver" per repository. Most, or all, other repositories have a single source of truth which makes it easier to resolve. Don't worry if you lost me :)

Something else that wonders me is the domain/endpoint of the API. It's only isolated with the `v2` part (like in FigShare), however, nothing informs me this is the API. I would expect `https://api.data.4tu.nl/v2/` or `https://data.4tu.nl/api/v2/`. 

I'm looking forward to future Djehuty updates!

**Comment by roelj** [comment]
I think I understand now. Going from the DOI to the corresponding API URL is an uncertain/fragile step.
For 4TU.ResearchData, searching for the DOI may be the shortest path to translate to the `url_public_api`:
```
$ curl -H "Content-Type: application/json" -H "Accept: application/json" https://data.4tu.nl/v2/articles/search -d '{ "search_for": "10.4121/21989216.v1"}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   955  100   917  100    38   9344    387 --:--:-- --:--:-- --:--:--  9845
[
  {
    "id": 21989216,
    "uuid": "17e3e0e3-55a2-47d0-bc22-4cb470f3882b",
    "title": "Data on the geographical distribution of Mimosa bimucronata in China",
    "doi": "10.4121/21989216.v1",
    "handle": null,
    "url": "https://data.4tu.nl/v2/articles/17e3e0e3-55a2-47d0-bc22-4cb470f3882b",
    "published_date": "2023-02-02T10:10:18",
    "thumb": "",
    "defined_type": 3,
    "defined_type_name": "dataset",
    "group_id": 28598,
    "url_private_api": "https://data.4tu.nl/v2/account/articles/17e3e0e3-55a2-47d0-bc22-4cb470f3882b",
    "url_public_api": "https://data.4tu.nl/v2/articles/17e3e0e3-55a2-47d0-bc22-4cb470f3882b",
    "url_private_html": "https://data.4tu.nl/my/datasets/17e3e0e3-55a2-47d0-bc22-4cb470f3882b/edit",
    "url_public_html": "https://data.4tu.nl/datasets/17e3e0e3-55a2-47d0-bc22-4cb470f3882b/1",
    "timeline": {
      "posted": "2023-02-02T10:10:18",
      "firstOnline": "2023-02-02T10:10:18",
      "revision": null
    },
    "resource_title": "",
    "resource_doi": ""
  }
]
```

The DOI prefix `10.4121` can be used to recognize that it's from 4TU.ResearchData.

Based on the flowchart for how Datahugger works: Could 4TU.ResearchData integrate better with re3data? What would that entail?

> Something else that wonders me is the domain/endpoint of the API. It's only isolated with the v2 part (like in FigShare), however, nothing informs me this is the API. I would expect https://api.data.4tu.nl/v2/ or https://data.4tu.nl/api/v2/.

Interesting observation!  What exactly is the problem here?

**Comment by J535D165** [comment]
> For 4TU.ResearchData, searching for the DOI may be the shortest path to translate to the url_public_api:

What a wonderful idea! Somehow, I never thought about this solution. It would be nice to explore. It won't solve all of my issues because I also want to load the dataset from the URL itself, but it is a nice and interesting fallback option. I will explore it!

> Based on the flowchart for how Datahugger works: Could 4TU.ResearchData integrate better with re3data? What would that entail?

This is an interesting question, and not only for Djehuty. I have been in contact with Re3Data, and it turns out there is a lot of manual work in Re3Data. On the tab "standards", you will see the API endpoints. One is still pointing to Figshare. It might be good to update this. It might also be good to align the name of the record in Re3Data with the name in datacite [4TU.ResearchData](https://search.datacite.org/repositories/delft.data4tu). This helps to resolve the DOI. 

> > Something else that wonders me is the domain/endpoint of the API. It's only isolated with the v2 part (like in FigShare), however, nothing informs me this is the API. I would expect https://api.data.4tu.nl/v2/ or https://data.4tu.nl/api/v2/.
> 
> Interesting observation! What exactly is the problem here?

Maybe only a matter of taste. It's slightly hard to predict how a URL responds. For example, an invalid dataset id in the REST API responds with a default HTML 404 page. This is different from the response of Figshare. This might be more intuitive if you isolate them further. But again, just a brainwave ;)

**Comment by roelj** [comment]
Thank you for suggesting improvements to how 4TU.ResearchData can/should handle DOI redirects. This is something we plan to unify, but we move slowly to ensure we don't break anything we weren't aware of.

I'll close this issue because I believe/hope you've found a way to make Datahugger work with/for djehuty. If not, please open a new issue with the specific issue(s).

Thank you again for your efforts!
