### ISSUE TITLE
Support for HEAD requests

### ISSUE THREAD

**Issue by J535D165** [4TUResearchData/djehuty#12]
Head requests in Djehuty are not supported (it seems)

```
% curl -IL https://doi.org/10.4121/21989216
HTTP/2 302 
date: Tue, 02 May 2023 07:08:35 GMT
content-type: text/html;charset=utf-8
content-length: 163
location: https://data.4tu.nl/articles/_/21989216
vary: Accept
expires: Tue, 02 May 2023 07:15:23 GMT
permissions-policy: interest-cohort=(),browsing-topics=()
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=55eysyg5MogNDv2RSeaRjSLbF7fUF6GDhuyI2Ith8Wj0Tyk2T5QKSDmFqH69XGGBEmNg8ljTuvazWYHwusrbT0v%2B9AZmLGx8UXaYSc828s1hNmiPScjuwaPqG7Nxl2%2BQJJJfJF8%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
server: cloudflare
cf-ray: 7c0e6f114cb40e35-AMS
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

HTTP/1.1 405 METHOD NOT ALLOWED
Server: nginx/1.20.1
Date: Tue, 02 May 2023 07:08:38 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 23
Connection: keep-alive
Strict-Transport-Security: max-age=63072000
```

This makes it hard for many services to validate/resolve the URL.

**Comment by roelj** [comment]
Thanks @J535D165 for reporting this.

I began implementing support for `HEAD` requests in [e5ec0e9](https://github.com/4TUResearchData/djehuty/commit/e5ec0e919c0b49b0bf86995fbf9b9a31ebd838d3), so for your example/use case it should be resolved. Please don't forget to pass an `Accept` header:
```
curl -H "Accept: text/html" -IL https://doi.org/10.4121/21989216
```

The implementation of `HEAD` is incomplete, but I will gradually implement the missing cases in the coming days.

Out of curiosity, do you know which services (of the many) had issues because we didn't support `HEAD` requests?

**Comment by roelj** [comment]
I implemented support for the `HEAD` calls for the remainder of the `GET` calls in [64cc03d](https://github.com/4TUResearchData/djehuty/commit/64cc03d7a9d0d1412244b10691db122fdfd498b3).

Could you let me know whether it's OK this way?

Thanks for your time!

**Comment by roelj** [comment]
As it seems you've solved the problem you were having, and I believe the `HEAD` method is now available I'm closing this issue. Please do not hesitate to (re)open this or another issue if there's anything else to be done regarding the `HEAD` method.

**Comment by J535D165** [comment]
Sorry bit behind schedule. Thanks for the implementation, it works out of the box!
