### ISSUE TITLE
Cannot run on local? - `Read-only file system: '/data'`

### ISSUE THREAD

**Issue by nsunami** [4TUResearchData/djehuty#17]
Hello! 

I followed the README to run the app on local. But when I run the `djehuty web` command, it will give me an error. Could anyone give me pointers so that I can run on local? 

----
Steps that I took:

1. Followed the README files code until [Interactive Environment](https://github.com/4TUResearchData/djehuty?tab=readme-ov-file#interactive-development) 
2. I ran `djehuty web --config-file djehuty.xml`
3. The command fails with the error: `OSError: [Errno 30] Read-only file system: '/data'`

**Comment by H-Kwon** [comment]
Hi @nsunami!

You might need to change two options in your `djehuty.xml` file.

```
  <storage-root>/home/nsunami/djehuty/data</storage-root>
  <cache-root clear-on-start="1">/home/nsunami/djehuty/data/data/cache</cache-root>
```

You can replace `/home/nsunami/djehuty` with your actual djehuty directory properly. The owner of the directories need to be the same as the user running the djehuty command so that the djehuty program can write the directories.

**Comment by nsunami** [comment]
Thanks, @H-Kwon! That makes total sense, and now it's running on my end 😎 

<img width="1218" alt="image" src="https://github.com/4TUResearchData/djehuty/assets/17035406/abc668a9-513b-42a3-9957-3ee329a8a99e">

Since my local username is `nami` I used:
```
  <storage-root>/Users/nami/home/data</storage-root>
  <cache-root clear-on-start="1">/Users/nami/data/cache</cache-root>
```


Thank you!

**Comment by H-Kwon** [comment]
@nsunami 

And one more tip. Please add your email address as your admin account in `<authentication>` and `<privileges>`. This will let you login immediately without any other authentication method such as OAuth.

```
  <authentication>
    <automatic-login-email>YOUR_EMAIL@example.com</automatic-login-email>
  </authentication>

  <privileges>
    <account email="YOUR_EMAIL@example.com" orcid="xxxx-xxxx-xxxx-xxxx">
      <may-administer>1</may-administer>
      <may-impersonate>1</may-impersonate>
      <may-review>1</may-review>
      <may-run-sparql-queries>1</may-run-sparql-queries>
    </account>
  </privileges>
```

P.S. The admin account is created by djehuty while being executed for the first time and reading the `djehuty.xml` file. If `<DJEHUTY_ROOT>/.djehuty-initialized` file already exists, then you need to follow these steps to create the admin account.

1. Make sure that your `djehuty.xml` file has been configured like the above.
2. Reset your database (Depends on <rdf-store> such as Virtuoso, Berkeley DB, In-memory DB..)
3. Delete `<DJEHUTY_ROOT>/.djehuty-initialized` file.
4. Execute `djehuty web` command with `--initialize` option.
5. Check the djehuty's log file to see if the initialization has been done properly.
