### ISSUE TITLE
Web - Find & Reuse menu item goes home

### ISSUE THREAD

**Issue by bbartholdy** [4TUResearchData/djehuty#18]
In the ABOUT YOUR DATA submenu, the Find & Re-Use option leads to https://data.4tu.nl/portal, which is just the homepage. I'm not sure if this is intentional or not, but it can be a little confusing and (to me at least) it seems like the link is missing. At least if you are already on the homepage.

I would probably recommend instead, if referring the user to the homepage was intended, sending the user to https://data.4tu.nl/search
since that is where you can find and re-use the datasets. Or it should go to a page with instructions on how to find and re-use datasets on 4TU (e.g., addressing licenses).

**Comment by roelj** [comment]
Your suggestion to let it refer to the search page makes a lot of sense to me.  I prepared the change, and it will go live in the evening today.

I will report back and close the issue when the change is applied.

Thank you @bbartholdy!

**Comment by roelj** [comment]
I applied the change. Thank you again @bbartholdy !
