### ISSUE TITLE
Missing name for remote in instrucitons to push git repo to 4TU

### ISSUE THREAD

**Issue by manuGil** [4TUResearchData/djehuty#22]
The instructions for adding the remote when creating a dataset for software is missing the remote name, for example `origin`

Correct command:
```sh
git remote add  origin http://127.0.0.1:8080/v3/datasets/68ddf857-711b-4469-915e-ad55316ec65f.git
```

**Comment by roelj** [comment]
Hi @manuGil. Thank you very much for participating in the hackathon, and for reporting this issue.
If I understand it correctly, the name can/must be configured in the configuration file using the `site-shorttag` option:
```
<djehuty>
  ...
  <site-shorttag>origin</site-shorttag>
</djehuty>
```

Considering that researchers usually push existing Git repositories that live on Github or Gitlab, which would be named `origin`, what would you consider a good fallback default?

**Comment by manuGil** [comment]
> Hi @manuGil. Thank you very much for participating in the hackathon, and for reporting this issue. If I understand it correctly, the name can/must be configured in the configuration file using the `site-shorttag` option:
> 
> ```
> <djehuty>
>   ...
>   <site-shorttag>origin</site-shorttag>
> </djehuty>
> ```
> 
> Considering that researchers usually push existing Git repositories that live on Github or Gitlab, which would be named `origin`, what would you consider a good fallback default?

We could use '4tu' for the name of the remote in this case. And also update the push instructions to be `git push 4tu --all`

**Comment by roelj** [comment]
I think setting the default value [at wsgi.py line 67](https://github.com/4TUResearchData/djehuty/blob/main/src/djehuty/web/wsgi.py#L67) will resolve this issue.

Would you like to create a patch or do you want me to create one? :-)

**Comment by manuGil** [comment]
> I think setting the default value [at wsgi.py line 67](https://github.com/4TUResearchData/djehuty/blob/main/src/djehuty/web/wsgi.py#L67) will resolve this issue.
> 
> Would you like to create a patch or do you want me to create one? :-)

It's fine if you can create it. Thank you for that.

**Comment by roelj** [comment]
Okay. I pushed the change in [4634324](https://github.com/4TUResearchData/djehuty/commit/4634324011a08849b2ae14f180839fd09206a835).
