### ISSUE TITLE
Mixed file and dataset URLs in the articles/{id} response

### ISSUE THREAD

**Issue by girgink** [4TUResearchData/djehuty#5]
This is a 4TU.ResearchData issue, please feel free to relocate if required.

/v2/articles/{id} endpoint returns Figshare URLs for old datasets, even if they are available in the new platform. This is problematic, because new access tokens are not valid for Figshare; hence, dataset operations cannot be performed by using the reported URLs.

**Comment by roelj** [comment]
Thank you for reporting this. I'm going to look into the URLs returned by the endpoint.

**Comment by roelj** [comment]
@girgink I believe the changes in [bdbb55e5](https://github.com/4TUResearchData/djehuty/commit/bdbb55e5c16bac3dbf768ea57f9c3fe4e8e00912) fix this problem. Would you be able to test whether this works "as expected" now?

Thank you!

**Comment by girgink** [comment]
@roelj Thanks for the fix. Dataset URLs seem to be corrected, but file URLs still refer to Figshare. Here is an example:

Dataset: https://data.4tu.nl/datasets/f94030a6-aac7-4539-882b-d43b7bf83897

```
{
    'files': [{
            'id': 39484261,
            'uuid': 'f5f4376b-e9d0-4f65-a1bd-3cc42d7a5d78',
            'name': 'AeoLiS-2.1.0.tar.gz',
            'size': 94476,
            'is_link_only': False,
            'download_url': 'https://ndownloader.figshare.com/files/39484261',
            'supplied_md5': 'b25cf84734bb2492bc08caea70132a19',
            'computed_md5': 'b25cf84734bb2492bc08caea70132a19'
        }
    ],
    ...
    'url_private_api': 'https://data.4tu.nl/v2/account/articles/f94030a6-aac7-4539-882b-d43b7bf83897',
    'url_public_api': 'https://data.4tu.nl/v2/articles/f94030a6-aac7-4539-882b-d43b7bf83897',
    'url_private_html': 'https://data.4tu.nl/my/datasets/f94030a6-aac7-4539-882b-d43b7bf83897/edit',
    'url_public_html': 'https://data.4tu.nl/datasets/f94030a6-aac7-4539-882b-d43b7bf83897/1',
    ...
}
```

**Comment by roelj** [comment]
@girgink Thank you for pointing out the `download_url`.  I adjusted it in [6f60b2c2](https://github.com/4TUResearchData/djehuty/commit/6f60b2c28ded178948f6b8870fa4b9e1604459cd).

**Comment by girgink** [comment]
Thanks a lot! I checked, it works correctly now.
