### ISSUE TITLE
Options relating to file(type)s ?

### ISSUE THREAD

**Issue by steltenpower** [4TUResearchData/djehuty#6]
I wonder if (for reasons of the I in FAIR) somewhere in this it would make sense to have any of the warnings below:
This file (extension) says it's of type X, but …
- … our X-validator says it's not up to spec(ification), with a link to the found warnings and errors.
- … X does not have an OPEN spec(ification).
- … X does not have an open implementation (or if it does, a link to a list of them)
- … X is not a type your archive wants/prefers (different colors)

**Comment by roelj** [comment]
Hi @steltenpower, these are great ideas! I think the main reason we don't have automated checks and a feedback mechanism for files and filetypes is that we don't have the development capacity to implement them.

Would you like to volunteer implementing checks (even lightweight checks)?  I'd be happy to review such implementation to integrate it with the current codebase.

**Comment by steltenpower** [comment]
If at some point I'll get some screen time available, where would I start?
I'm quite in the dark here.
I know a little bit about a lot of things, taught Carpentries Python, but routine … not so much.

**Comment by roelj** [comment]
That is an excellent question indeed, and thank you very much for offering help.
The way I see it, there are roughly two distinct steps:
1. Writing procedures that implement a check;
2. Call these procedures at the appropriate time in `djehuty`.

Step 1 would already be very helpful. I imagine we could start by having a procedure that takes a filepath as input, and returns errors/recommendations. We implement various validation procedures in [the `validator.py` module](https://github.com/4TUResearchData/djehuty/blob/main/src/djehuty/web/validator.py). So I imagine it may be a good fit to add these procedures to that module eventually.

Step 2 involves running a local instance of `djehuty`.  I began writing a set-up guide for a [development setup for `djehuty`](https://github.com/4TUResearchData/djehuty/blob/main/doc/contributing.tex).  The key insight is that `djehuty` is a Python package, and we use ORCID as identity provider for development. After configuring that, you should have a fully operational `djehuty`, and you could attempt to include the checks.  The procedure that validates other fields when a user clicks the "submit for review" button, can be [found here](https://github.com/4TUResearchData/djehuty/blob/main/src/djehuty/web/wsgi.py#L5613).

Feel free to reach out via e-mail as well. You can find my e-mail address in the Git log.
